const mongoose = require('mongoose')
const Schema = mongoose.Schema


let cricketSchema = new Schema({
    "NAME": String,
    "Full name": String,
    "BATTING_Tests_Mat": String,
    "BATTING_Tests_Inns": String,
    "BATTING_Tests_NO": String,
    "BATTING_Tests_Runs": String,
    "BATTING_Tests_HS": String,
    "BATTING_Tests_Ave": String,
    "BATTING_Tests_BF": String,
    "BATTING_Tests_SR": String,
    "BATTING_Tests_100": String,
    "BATTING_Tests_50": String,
    "BATTING_Tests_4s": String,
    "BATTING_Tests_6s": String,
    "BATTING_Tests_Ct": String,
    "BATTING_ODIs_Mat": String,
    "BATTING_ODIs_Inns": String,
    "BATTING_ODIs_No": String,
    "BATTING_ODIs_Runs": String,
    "BATTING_ODIs_HS": String,
    "BATTING_ODIs_Ave": String,
    "BATTING_ODIs_BF": String,
    "BATTING_ODIs_SR": String,
    "BATTING_ODIs_100": String,
    "BATTING_ODIs_50": String,
    "BATTING_ODIs_4s":String,
    "BATTING_ODIs_6s":String,
    "BATTING_ODIs_Ct":String,
    "BATTING_ODIs_Mat":String,
    "BATTING_ODIs_Inns":String,
    "BATTING_ODIs_No":String,
    "BOWLING_Tests_Wkts":String,
    "BOWLING_Tests_Econ":String,
    "BOWLING_Tests_4w":String,
    "BOWLING_Tests_5w":String,
    "BOWLING_Tests_10":String,
    "BOWLING_ODIs_Inns" :String,
    "BOWLING_ODIs_Wkts":String,
    "BOWLING_ODIs_Econ":String,
    "BOWLING_ODIs_4w":String,
    "BOWLING_ODIs_5w":String,
    "BOWLING_ODIs_10":String,
})

module.exports = mongoose.model("Cricket", cricketSchema)